services:
  postgres:
    image: postgres:16
    container_name: dormitory_postgres
    restart: always
    environment:
      POSTGRES_USER: dorm_user
      POSTGRES_PASSWORD: dorm_password
      POSTGRES_DB: dormitory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: dormitory_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: